config/routes.rb
Rails.application.routes.draw do
  resources :vcards

end

app/models/vcard.rb
class Vcard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vcards_controller.rb
class VcardsController < ApplicationController
  before_action :set_vcard, only: [:show, :edit, :update, :destroy]

  # GET /vcards
  # GET /vcards.json
  def index
    @vcards = Vcard.all
  end

  # GET /vcards/1
  # GET /vcards/1.json
  def show
  end

  # GET /vcards/new
  def new
    @vcard = Vcard.new
  end

  # GET /vcards/1/edit
  def edit
  end

  # POST /vcards
  # POST /vcards.json
  def create
    @vcard = Vcard.new(vcard_params)

    respond_to do |format|
      if @vcard.save
        format.html { redirect_to @vcard, notice: 'Vcard was successfully created.' }
        format.json { render :show, status: :created, location: @vcard }
      else
        format.html { render :new }
        format.json { render json: @vcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vcards/1
  # PATCH/PUT /vcards/1.json
  def update
    respond_to do |format|
      if @vcard.update(vcard_params)
        format.html { redirect_to @vcard, notice: 'Vcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @vcard }
      else
        format.html { render :edit }
        format.json { render json: @vcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vcards/1
  # DELETE /vcards/1.json
  def destroy
    @vcard.destroy
    respond_to do |format|
      format.html { redirect_to vcards_url, notice: 'Vcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vcard
      @vcard = Vcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vcard_params
      params[:vcard]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vcards_helper.rb
module VcardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VcardImporter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vcards/_form.html.erb
<%= form_for(@vcard) do |f| %>
  <% if @vcard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vcard.errors.count, "error") %> prohibited this vcard from being saved:</h2>

      <ul>
      <% @vcard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vcards/edit.html.erb
<h1>Editing vcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @vcard %> |
<%= link_to 'Back', vcards_path %>

app/views/vcards/index.html.erb
<h1>Listing vcards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vcards.each do |vcard| %>
      <tr>
        <td><%= link_to 'Show', vcard %></td>
        <td><%= link_to 'Edit', edit_vcard_path(vcard) %></td>
        <td><%= link_to 'Destroy', vcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vcard', new_vcard_path %>

app/views/vcards/new.html.erb
<h1>New vcard</h1>

<%= render 'form' %>

<%= link_to 'Back', vcards_path %>

app/views/vcards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_vcard_path(@vcard) %> |
<%= link_to 'Back', vcards_path %>